const ShopActionTypes = {
   FETCH_COLECTIONS_START : 'FETCH_COLECTIONS_START',
   FETCH_COLECTIONS_SUCCESS : 'FETCH_COLECTIONS_SUCCESS',
   FETCH_COLECTIONS_FAILURE : 'FETCH_COLECTIONS_FAILURE',
}
export default ShopActionTypes;